### ISSUE TITLE
Too much video_decodeRIL:image pool allocated for H.264 samples with varying REF(1 to 16)

### ISSUE THREAD

**Issue by brunogm0** [popcornmix/omxplayer#236] opened 2014-08-14 21:47 UTC
Samples with 1Ref count show in vcdbg reloc, 7 image pools that correctly follow the resolutionX subsampling size. So  1920x1080p with 4:2:0(1.5Bytes) has 3M, 720p has 1.4M, 1920x800 has 2.3M and so on.  Even with  720p main profile samples too much image_pools were allocated that reduced available resources for video_fifo and was the main reason for the need of more memory to decode files and stuttering.  If solved video_fifo can be set at 1s duration even for 16Ref files, solving stuterring and there will be hardlly a reason to set GPU_mem above 80M.

1Ref samples shows 7 pools.
2Ref samples shows 7 or 8 pools.  
**3Ref samples shows 7 or 8 pools.  
4Ref samples shows 8 pools.
5Ref samples shows 8 pools.
6Ref samples shows 10 pools.
8Ref sample shows 12 pools
9Ref sample shows 13 pools.
16Ref sample shows 20 pools.

**Samples are L5.1 main and high profile with MP stuttering because it needs more than 20M video_fifo for a 0.3s fifo time in difficult scenes.

**Comment by popcornmix** [comment] 2015-01-25 16:10
Closing as duplicate of https://github.com/raspberrypi/firmware/issues/337

**Closed by popcornmix** 2015-01-25 16:10 UTC
