### ISSUE TITLE
2 videos on different Dbus names interaction when paused 

### ISSUE THREAD

**Issue by clacktronics** [popcornmix/omxplayer#349] opened 2015-04-29 16:50 UTC
I have 2 copies of omxplayer launched, ones dbus name is standard `org.mpris.MediaPlayer2.omxplayer` the other is named (using --dbus_name ) `org.mpris.MediaPlayer2.omxplayer2` using the supplied dbuscontrol.sh script as a test send `dbuscontrol.sh pause` works sometimes but other times it seems to interact with the other re-named dbus.

Specifically 
If I pause one it mutes the other
if I pause one then unpause it the other pauses then comes back
Sometimes the other gets stuck on a frame.

Is this an error or am I perhaps using omxplayer beyond its intended purpose!

**Comment by popcornmix** [comment] 2015-04-29 19:23
Duplicate of https://github.com/popcornmix/omxplayer/issues/317

**Closed by popcornmix** 2015-04-29 19:23 UTC

**Comment by clacktronics** [comment] 2015-04-30 16:07
thanks!
