### ISSUE TITLE
How to terminate an omxplayer with kill command?

### ISSUE THREAD

**Issue by hanyuwei70** [popcornmix/omxplayer#409] opened 2016-01-04 10:08 UTC
I am developing a program to distribute video signals on rpi and used omxplayer. But when I send SIGTERM to omxplayer it doesn't stop.

There are 2 processes when I run omxplayer

    /bin/bash /usr/bin/omxplayer rtmp://--/livetv/--.flv
    /usr/bin/omxplayer.bin rtmp://--/livetv/--.flv

So I send SIGTERM to the first process, it disappeared from `ps`. But second is still alive and the video is still playing.

How can I terminate them both without put a `^C` into stdin?

**Comment by subogero** [comment] 2016-01-07 21:42
Always kill the `omxplayer.bin` process. The first one is just a script to start it.

**Comment by jehutting** [comment] 2016-01-29 07:04
Duplicate of https://github.com/huceke/omxplayer/issues/253

**Comment by jehutting** [comment] 2016-05-10 13:09
@hanyuwei70 I think this one can be closed as your question is also answered in the huceke repository.

**Closed** 2016-06-22 19:33 UTC
