### ISSUE TITLE
Omxplayer quits playback when sd card full?

### ISSUE THREAD

**Issue by ffloress** [popcornmix/omxplayer#486] opened 2016-09-30 00:54 UTC
While performing a huge cloud sync, the sd card got full.
At this same time, omxplayer was playing a list of movies. Suddenly omxplayer started to quit playback of some movies (not all)
This happened along many hours until I found the sd card was full, and the sync job was trying to finish its job..
I wonder why Omxplayer would quit if the sd card get full. Does it need some disk space to create buffer?

Thank you.

**Comment by jehutting** [comment] 2016-10-09 08:34
AFAIK OMXPlayer creates only at startup  ```/tmp/omxplayerdbus.${USER:-root}``` and
```/tmp/omxplayerdbus.${USER:-root}.pid``` and only  when the pid file doesn't already exist.

I don't know if any library, ffmpeg, openmax, etc. does; I don't think they do.

I copied files to my /tmp folder until the sd card got full (```df``` shows 100% Use for my /dev/root').
OMXPlayer is still able to play a movie without a fault.

Strange however is that you say that some files do play and some don't. Are the non-playing movies all of the same type?

**Comment by popcornmix** [comment] 2016-10-10 11:18
omxplayer doesn't write to sdcard apart from in the wrapper script @jehutting referred to and optionally if the debug log is enabled.

I suspect the issue is more linux related. Linux uses files for everything, and almost no apps work reliably when the sdcard is full.

**Comment by popcornmix** [comment] 2016-11-01 14:01
Closing as I don't think there is anything omxplayer can do here.

**Closed by popcornmix** 2016-11-01 14:01 UTC
