### ISSUE TITLE
Very loud audio by default

### ISSUE THREAD

**Issue by mariomadproductions** [popcornmix/omxplayer#751] opened 2019-10-31 20:55 UTC
Maybe this isn't something that can be solved, as for others the audio might be very quiet by default, and you can change the volume at startup (i'm using it from the command line). But maybe this is a valid issue? This is on raspbian on rpi3b. omxplayer version: 20190723+gitf543a0d-1.

**Comment by popcornmix** [comment] 2019-11-01 13:02
Duplicate of https://github.com/popcornmix/omxplayer/issues/750

**Closed by popcornmix** 2019-11-01 13:02 UTC

**Comment by mariomadproductions** [comment] 2019-11-01 13:23
Oops, didn't notice I made that.
