### ISSUE TITLE
Embedded subtitles in vob files are not shown/detected

### ISSUE THREAD

**Issue by wizkids** [popcornmix/omxplayer#407] opened 2016-01-04 02:33 UTC
Using preinstalled Raspbian (jesse) on Raspberry Pi 2 (with MPEG-2 license) and standalone OMXPlayer (pre-installed - using apt-get install I assume):

    omxplayer - Commandline multimedia player for the Raspberry Pi
        Build date: Sat, 12 Sep 2015 00:49:19 +0000
        Version   : d99bd86 [master]

I'm playing Vob files from mounted ISO files (DVD rips with everything but main video + audio (AC3 or DTS) + 1/2 subtitle tracks removed).

Some times the subtitle tracks are detected, some times not. Regardless, the subtitles are not shown.

CLI output:

    pi@SRS-PI-2 /mnt/dvd/VIDEO_TS $ omxplayer -o hdmi VTS_01_1.VOB
    Video codec omx-mpeg2 width 720 height 576 profile 4 fps 25.000000
    Audio codec ac3 channels 6 samplerate 48000 bitspersample 16
    Subtitle count: 0, state: off, index: 1, delay: 0
    V:PortSettingsChanged: 720x576@25.00 interlace:0 deinterlace:0 anaglyph:0 par:1.42 layer:0 alpha:255
    Stopped at: 00:00:04
    have a nice day ;)
    
    pi@SRS-PI-2 /mnt/dvd/VIDEO_TS $ omxplayer -o hdmi VTS_01_2.VOB
    Video codec omx-mpeg2 width 720 height 576 profile 4 fps 25.000000
    Audio codec ac3 channels 6 samplerate 48000 bitspersample 16
    Subtitle count: 2, state: off, index: 1, delay: 0
    V:PortSettingsChanged: 720x576@25.00 interlace:0 deinterlace:0 anaglyph:0 par:1.42 layer:0 alpha:255
    Subtitle count: 2, state:  on, index: 1, delay: 0
    Subtitle count: 2, state:  on, index: 2, delay: 0
    Subtitle count: 2, state:  on, index: 1, delay: 0
    Stopped at: 00:00:23
    have a nice day ;)
    
    pi@SRS-PI-2 /mnt/dvd/VIDEO_TS $ omxplayer -o hdmi VTS_01_3.VOB
    Video codec omx-mpeg2 width 720 height 576 profile 4 fps 25.000000
    Audio codec ac3 channels 6 samplerate 48000 bitspersample 16
    Subtitle count: 0, state: off, index: 1, delay: 0
    V:PortSettingsChanged: 720x576@25.00 interlace:0 deinterlace:0 anaglyph:0 par:1.42 layer:0 alpha:255
    Stopped at: 00:00:01
    have a nice day ;)

Subtitles work in both ISO/Vob files when played in VLC (on PC) and on my Popcorn Hour (ISO only, haven't tried with Vob).

For obvious reasons I can't provide sample vidoes, but I'm willing to run some local tests if that'll help.

**Comment by jehutting** [comment] 2016-01-25 23:07
See issue #302

**Comment by popcornmix** [comment] 2016-01-26 13:43
Not supported. Duplicate of #302.

**Closed by popcornmix** 2016-01-26 13:43 UTC
