### ISSUE TITLE
2 instances of omxplayer using mpeg2 causes gpu lockup

### ISSUE THREAD

**Issue by jmeiners** [popcornmix/omxplayer#386] opened 2015-10-29 15:31 UTC
If you play 2 instances of omxplayer (windowed display) and both are using mpeg2 sources the gpu both videos will freeze and the gpu will stop responding to any vc commands till rebooted.  (mpeg2 is licensed)

Is there a hardware/software limitation to only a single mpeg2 stream?

**Comment by VittGam** [comment] 2015-10-29 15:48
Have you tried increasing the RAM allocated to the GPU to at least 128 MB? You can do it with `gpu_mem` in `/boot/config.txt`, or via `raspi-config`.

**Comment by jmeiners** [comment] 2015-10-29 16:00
Yes, using 196M gpu on a pi2.
It can run 6+ instances if it is h.264, but only 1 if mpeg2

**Comment by carlonluca** [comment] 2015-10-29 18:51
Probably not the same issue, but it seems similar to raspberrypi/firmware#449. Although the problem is related also to h264 there.

**Comment by jmeiners** [comment] 2015-10-29 19:28
Not really.  This lockup happens immediately every time.

**Comment by carlonluca** [comment] 2015-10-29 19:31
If you read all the messages you'll see that I can reproduce the same (or very similar) freeze in a few seconds when I run multiple players concurrently. The backtrace in every case is very similar (you'll have to read the messages after the first report).

**Comment by carlonluca** [comment] 2015-10-29 19:35
Also maybe related to #379.

**Comment by jmeiners** [comment] 2015-10-29 19:46
I think I have also seen the lockup you are referring to.  Very rare but can happen.

This issue is I can run lots of h.264 instances but only 1 mpeg2.

**Comment by carlonluca** [comment] 2015-10-29 19:49
If I run multiple players I get a complete lock of the GPU in a few seconds. If I run a single player I have a very rare lock, maybe related to frequent seek or however not sure. But I typically see both on h264. If you can run on gdb your omxplayer you may compare you backtraces with the ones I reported.

**Comment by gkreidl** [comment] 2015-11-01 11:58
I suppose it's a firmware issue. I could play up to four SD MPEG TS channels a short while ago (before upgrading to Jessie) with the same omxplayer version, Now it doesn't work any more.

**Comment by jmeiners** [comment] 2015-11-01 16:27
Do you recall what firmware version you were running (that worked)?

**Comment by popcornmix** [comment] 2015-11-02 15:17
Try with --nodeinterlace - I suspect that will work.

It's the change to the QPU deinterlacer which causes this. It grabs a lock on the QPUs which prevents a second stream from also using QPU deinterlace.
I'll see if we can either fall back to VPU deinterlace if QPU is not available, or whether we can share for SD resolutions.
1080i deinterlace is never going to support multiple streams (it's very expensive for GPU).

**Comment by gkreidl** [comment] 2015-11-02 16:04
it does work and now I know why it always worked for me until a short while ago: for some reason I had --deinterlace in my live-tv options (a special settings field in omxplayerGUI).

**Comment by jmeiners** [comment] 2015-11-02 16:26
You, my friend, are a genius :)
Is that locking done in the open source interface lib or the gpu?

**Comment by popcornmix** [comment] 2015-11-02 16:27
It's in the firmware. I'm looking into it.

**Comment by popcornmix** [comment] 2015-11-02 17:03
Can you test: https://dl.dropboxusercontent.com/u/3669512/temp/firmware_multideint.zip

**Comment by jmeiners** [comment] 2015-11-04 03:02
That firmware actually crashes my pi2.  I am running a custom kernel though, so probably not the best test subject.  Maybe someone of a recent kernel can try it?

**Comment by popcornmix** [comment] 2015-11-04 13:15
How does it crash? Do you get rainbow splash screen? Do you get any kernel console log? Can you log in?

**Comment by jmeiners** [comment] 2015-11-04 15:21
Very strange.  The device will lock up (custom screen saver freezes, ssh freezes, etc).  Sometimes it will recover for awhile and then lock up again.  This is just after boot, not running omxplayer.  Seems unlikely to have anything to do with your specific change.
My systems are firmware/kernel locked down so I can't actually use a firmware update anyway.  I'm perfectly happy with using --nodeinterlace for the windowed display case (thanks again).  The quality difference isn't a big deal in the smaller window.

**Comment by popcornmix** [comment] 2015-11-04 16:48
@gkreidl are you able to test the dropbox firmware?

**Comment by gkreidl** [comment] 2015-11-04 16:50
Sorry, not at the moment.

Am 04.11.2015, 17:48 Uhr, schrieb popcornmix <notifications@github.com>:

**Comment by popcornmix** [comment] 2015-11-07 11:43
The fix is in latest rpi-update firmware. I can now play 4 SD videos with deinterlace.

**Closed** 2015-12-07 15:52 UTC
